# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineTicketApp', '0002_plane_numbers_of_seats_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='certificate_of_identity_card',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_telephone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
