# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineTicketApp', '0005_auto_20171017_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seattype',
            name='seat_class_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
