# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineTicketApp', '0010_auto_20171022_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='book',
        ),
        migrations.RemoveField(
            model_name='ticketbook',
            name='flight',
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AirlineTicketApp.Flight'),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketbook',
            name='book_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_info', to='AirlineTicketApp.BookInfo'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airport_mid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AirlineTicketApp.Airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
