# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineTicketApp', '0011_auto_20171022_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrive_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='arrive_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_time',
            field=models.TimeField(null=True),
        ),
    ]
